### ISSUE TITLE
Tesla presence seems unreliable

### ISSUE THREAD

**Issue by etherbrat** [tesla-local-control/tesla_ble_mqtt_docker#65]
Just a heads-up, not an issue until confirmed by someone else. Twice in two days the Presence has remained “Away” after I returned to the garage from an outing. The only way I could restore correct operation was by rebooting my HA machine (RPi5, HA in a Container, located right beside the Tesla in the garage). The Pi5 talks WiFi to an access point which is also located in close proximity. The Tesla shows up in BLE Hero on my phone. I do not have the HA BLE Tracker installed. As best I can recall, the Presence indication has been quite accurate and responsive prior to this. Sumer is warming up the garage down here in AU, so it may be a chip temperature problem, although I do have the Pi in an enclosure with a fan.

**Comment by etherbrat** [comment]
It happened again today. Three times in a row now.

**Comment by iainbullock** [comment]
Others have reported similar issues. I have not had the issue myself and have been unable to reproduce. Temperature might be a factor, it's winter here in the UK so no chance of it getting too hot for me

**Comment by etherbrat** [comment]
Hi Iain,I don’t know if your stuff and the iBeacon tracker play together (I’m guessing that you don’t even use the beacon), but I am going to try to compare their outputs. I might also build the ESPHome ESP32 iBeacon hub and see what it says. Neil Higgins ***@***.*** 19 Nov 2024, at 6:26 PM, Iain Bullock ***@***.***> wrote:﻿
Others have reported similar issues. I have not had the issue myself and have been unable to reproduce. Temperature might be a factor, it's winter here in the UK so no chance of it getting too hot for me

**Comment by etherbrat** [comment]
I have Googled around a bit (a sad excuse for research, I admit) and I must say I can’t find any confirmation that the Model Y puts out a conforming iBeacon. That leaves open the question as to why Presence ever worked for me (if it relies on an iBeacon) but might also explain why it stopped working (I have recently had two Tesla software updates in quick succession). So if I can scan for Bluetooth devices of any kind (not just iBeacons), I might have better luck. Neil Higgins ***@***.*** 20 Nov 2024, at 2:40 AM, Iain Bullock ***@***.***> wrote:﻿
Not sure. I am experimenting with https://gateway.theengs.io/ to track my Apple watch using the same RPi. Seems to work fine. I therefore suggest you can run another iBeacon tracker on the same device, which might turn out to be more reliable than the Presence detection used on this project

**Comment by etherbrat** [comment]
FWIW, I took a deep breath and had a look at the _core source code. It appears (to me) that Presence is not derived from an iBeacon. And for the fourth day in a row, my Tesla is shown as “Away” when it’s at home. It behaved in more-or-less random fashion between about 5:30am and 11:00am, then settled to “Away”.

**Comment by iainbullock** [comment]
Sorry I misunderstood your previous quetion. You are right the code doesn't look for iBeacons it just scans for the BLE MAC; which should work reliably, but clearly it doesn't. 

I recommend you try turning off Presence detection in this code and using another docker container on your device which can provide the required functionality. I haven't tested any project for doing this for the car, but as I said earlier I have got  https://gateway.theengs.io working for tracking my Apple watch, so maybe it can be configured to track your car

**Comment by etherbrat** [comment]
Yes, I’ll try that.

 

I have raised an Issue on the _core project – hopefully their powers of diagnosis are better than mine.

 

Cheers,

Neil

**Comment by iainbullock** [comment]
I'm a dev on the core project too, so it might become a circular conversation. 

@raphmur @baylanger have a look to see what you think, there are issues with presence detection but I can 't replicate it myself

**Comment by etherbrat** [comment]
Good for you! (seriously). Bear in mind that I am now uncertain whether charge rate setting controls will get to the Tesla when the Presence is “Away”. If not, the whole bloody exercise is pointless, yah?Neil Higgins ***@***.*** 20 Nov 2024, at 5:22 PM, Iain Bullock ***@***.***> wrote:﻿
I'm a dev on the core project too, so it might become a circular conversation.
@raphmur @baylanger have a look to see what you think, there are issues with presence detection but I can 't replicate it myself

**Comment by iainbullock** [comment]
As long as the car is not really away, the commands will still work. The presence detection and command sending are completely seperate and independent of each other in the code. Others who have reported this issue have found command sending still works even when presence doesn't

**Comment by etherbrat** [comment]
That’s reassuring. Thanks. Neil Higgins ***@***.*** 20 Nov 2024, at 6:55 PM, Iain Bullock ***@***.***> wrote:﻿
As long as the car is not really away, the commands will still work. The presence detection and command sending are completely seperate and independent of each other in the code. Others who have reported this issue have found command sending still works even when presence doesn't

**Comment by iainbullock** [comment]
RPis with built in BLE seem to be good (I'm using RPi3b+). Many people report issues with USB devices. Probably depends exactly which type you have.

**Comment by jipema** [comment]
Just chiming in as I'm encountering the same issue from time to time. 
If there is anything I can do to help with troubleshooting, please let me know.

**Comment by iainbullock** [comment]
See here. Work in progress to resolve what I believe is causing this for many people. In the meantime if you have automations trying to send commands when the car is away it will definately cause problems

https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/142

**Comment by iainbullock** [comment]
I have implemented improvments into v0.4.3b-dev which is on DockerHub. Main changes are robustness improvements, see the CHANGELOG.

**Comment by iainbullock** [comment]
Interesting. There are two 'presences' being reported here:
```
Car is present and awake VIN:LRW3XXXXXXXXXXX, sending command
```
This one is derived from a call to body-controller-state and results in the Presence_BC binary_sensor in HA. It should get updated during the polling
```
vin:LRW3XXXXXXXXXXX presence has expired, set presence OFF
```
This is derived from a passive bluetooth scan i.e. doesn't talk to the car at all. It results in the Presence binary_sensor in HA. It doesn't get updated duirng the polling it is done seperately

I am currently recommending that the passive presence is used as I find it more reliable, and it gets updated more often. However maybe you could compare trends to see how they compare on your system over time

**Comment by jipema** [comment]
@iainbullock indeed, after 2 days relying on the presence_bc sensor, it seems quite reliable (had to look for it, since it's disabled by default).

**Comment by iainbullock** [comment]
Both presence entities work reliably on my setup, but I know it's not the case for some. I will therefore continue to offer both which the user can decide which is best for them, or maybe even apply some logic in a HA to use both

**Comment by xitation** [comment]
As a tip if you want a device_tracker entry in Homeassistance add this into an MQTT sensor:

Put your VIN in there... Or use MQTT Explorer to copy the exact topic path.

`- device_tracker:
    name: Tesla-MQTT Presence
    state_topic: "tesla_ble/%VIN%/binary_sensor/presence_bc"
    payload_home: "true"
    payload_not_home: "false"`

Maybe add this to the docs for this project, as I required a real device_trackor instead of a binary_sensor for presence detection in some automations blueprints I'm using.

**Comment by iainbullock** [comment]
@xitation agreed, thanks for the suggestion. I will look at including this in the forthcoming release.

**Comment by xitation** [comment]
Hey, after more digging tonight I suspect the issues I was facing was the use of a secondary USB Bluetooth 5* Realtec radio which was throwing errors in dmesg. I've ditched that, upgraded the Rasbian OS to latest, and using onboard BLE radio.

Will see if that improves things. 

Great project, really appreciate it!

I'll report back if I'm still having problems in case you need any debug info or something to help get to the bottom of the issue.

For others facing this, check your dmesg for any errors related to the bluetooth radio. 

I was seeing things like this:

**Comment by dettofatto** [comment]
I'm using these two sensors together. I've combined for having a third sensor.
If one of these are "home", my third sensor says "home".
Now I'm covering all time untill reboot (yes, I'm a fan  of rebooting all my HW during the night, I'm sorry...).

![Image](https://github.com/user-attachments/assets/1862fbf9-4817-450d-9b93-6dafeb8aa971)

**Comment by dettofatto** [comment]
I'm improving this presence with more automation.
But...
Now I've 
binary_sensor.tesla_ble_lrw_presence_bc
device_tracker.tesla_ble_lrw_presence_bc
binary_sensor.tesla_ble_lrw_presence

And my presence is gone... Why? It's wrong?

**Comment by iainbullock** [comment]
I don't know this is the unresolved issue. 

When I've got the new production release completed, I will spend some time trying to figure it out. Probably by reviewing the docker logs against the HA trend for the sensors to see if there's a clue 

What happens when the car returns can you send commands or do you have to restart the container to get it to work again?

**Comment by dettofatto** [comment]
Yes. I must restart the container. In the first Tesla I've this issue (rpi4). In the second (rpi2) is more stable. Maybe I must disable all bc ?

**Comment by xitation** [comment]
Appears the new device_tracker entity has some bugs :)

<img width="356" alt="Image" src="https://github.com/user-attachments/assets/9343252c-651f-441c-96c2-28ad1e8256db" />

**Comment by dettofatto** [comment]
Yes...
I'm in the same situation and it's not constant.
With 2 cars, with 2 different hw

![Image](https://github.com/user-attachments/assets/a0cf02dd-1dfe-465d-9a14-d0890941f901)

![Image](https://github.com/user-attachments/assets/e2de6f38-940d-4e92-8bfd-4279dcb63a2e)

**Comment by xitation** [comment]
Just for comparison of sensor stability this is the data of presence for the 3 sensors over the past week.

<img width="1258" alt="Image" src="https://github.com/user-attachments/assets/d842c033-d948-4962-9bc7-9a70f00c0644" />

I made some config changes on Feb19 to the RPi 4 which appear to have maybe improved stability on the sensors... And I don't see any HCI errors in dmesg since making the following changes either.

**What I did:**. 
1. Ran rpi-update to update to latest kernel and firmware. 

2. Disabled sap by chaging the systemd unit for bluetooth.service to use this. 
ExecStart=/usr/libexec/bluetooth/bluetoothd --noplugin=sap

3.  Added the following 2 configurations to /etc/bluetooth/main.conf. 
FastConnectable = true
TemporaryTimeout = 0

Look at the changes in the sensor stability before and after these changes, I can see a pretty decent improvement in how often it flip/flops on even the non BC sensor.

More testing i'd say will help prove the value of these changes, but if it does pan out to improve for others, might be worthwhile adding into the docs these changes :)

**Comment by iainbullock** [comment]
@xitation this is very interesting thanks for posting. I will look at the bluetooth parameters you changed. Did you have a reference for these which explains what they do?

Here's mine which is much less noisy. I haven't made any changes to the default bluetooth settings. When Presence was Unknown on Tuesday, I had turned the power off to my house:

<img width="928" alt="Image" src="https://github.com/user-attachments/assets/1891963f-6fb8-40b7-a070-cc0a763ef109" />

**Comment by dettofatto** [comment]
![Image](https://github.com/user-attachments/assets/2356ca18-84e1-4b6b-8bbd-6dceec8561ab)

**Comment by iainbullock** [comment]
To get timestamps in your docker logs try this:

`docker logs -t tesla_ble_mqtt`

If you want to obsfurcate the VINs and dump the output into a file do this:

```
export VIN1=whateverVIN1
export VIN2=whateverVIN2
docker logs -t  tesla_ble_mqtt | sed -e "s/$VIN1/VIN1xxx/g" -e "s/$VIN2/VIN2xxx/g" > output.txt`
```
You can then edit the file to extract what is of interest

**Comment by xitation** [comment]
> [@xitation](https://github.com/xitation) this is very interesting thanks for posting. I will look at the bluetooth parameters you changed. Did you have a reference for these which explains what they do?
> 
> Here's mine which is much less noisy. I haven't made any changes to the default bluetooth settings. When Presence was Unknown on Tuesday, I had turned the power off to my house:
> 
> <img alt="Image" width="928" src="https://private-user-images.githubusercontent.com/59146297/415558899-1891963f-6fb8-40b7-a070-cc0a763ef109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAzNjc0NTYsIm5iZiI6MTc0MDM2NzE1NiwicGF0aCI6Ii81OTE0NjI5Ny80MTU1NTg4OTktMTg5MTk2M2YtNmZiOC00MGI3LWEwNzAtY2MwYTc2M2VmMTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDAzMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMDY0NzEzNmNhZGZjMTYyMjc5YjgzMWVmODdhNjAyZDUyYWY2ZTA5N2EyYThhZWZlYzVjNDhmN2RjYzMwNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YoNs6cFkXsjZL8xU9kBLeW2-z5EFQ8zRgTdMzf1H1j4">
> The is one glitch in this, see:
> 
> <img alt="Image" width="550" src="https://private-user-images.githubusercontent.com/59146297/415559829-c8dbb452-904c-4597-be31-323016ea46fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAzNjc0NTYsIm5iZiI6MTc0MDM2NzE1NiwicGF0aCI6Ii81OTE0NjI5Ny80MTU1NTk4MjktYzhkYmI0NTItOTA0Yy00NTk3LWJlMzEtMzIzMDE2ZWE0NmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDAzMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZTg1Mzc0OWJlNWE0NWQzZWVkMTg3NTgyYTNmMGNkNmI0M2I0MWM4YjFmOGQwOTRiMDE3NDg3NmI5ZjE1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qGODwjYJphfxZfVqHmyB1Mi7dzthX4Z04A_LNIwzYJU">
> This was from 05:58:30 until 05:58:36 / 06:03:17, this was when HA restarted after I updated a custom component in HACS:
> 
> <img alt="Image" width="757" src="https://private-user-images.githubusercontent.com/59146297/415562524-def2ec25-a271-471c-a55e-274ff5b100f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAzNjc0NTYsIm5iZiI6MTc0MDM2NzE1NiwicGF0aCI6Ii81OTE0NjI5Ny80MTU1NjI1MjQtZGVmMmVjMjUtYTI3MS00NzFjLWE1NWUtMjc0ZmY1YjEwMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDAzMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMGY2MWE1YTA3MjdkZmMzM2Y0Y2E4NTM3MGQ0MzMxMGZlYTE3NzkwYzFlYmFkY2IxNzk0NjQ1YmZmNDk0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SIqJIaCOuv3v-Tiqii5-57-KsnuAHhKFTIpDmqyjx2U">

The SAP stuff is a module related to being able to read simcards for modems, it's not required and I disabled it due to constant errors of the service not being happy due to no device with simcard / modem etc. Also I removed Modemmanager which probably broke that module. 

The other 2 parameters are described in the config file. But I found them suggested on a post somewhere related to RPi bluetooth reliability not being great, and they were suggested to help improve this.  https://www.makeuseof.com/fix-bluetooth-connectivity-issues-in-ubuntu/ provided a bit of info too.

**Comment by dettofatto** [comment]
I've resolved with an esp32 and 2 Tesla:

```
esphome:
  name: scannerbt_auto
  friendly_name: Sensore BT Presenza Auto Garage

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DT0/xxx+1qy4="

ota:
- platform: esphome
  password: "xxxx"

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
  manual_ip:
    static_ip: 192.x,x  # Scegli un IP libero nella tua rete
    gateway: 192.x.x      # IP del tuo router 
    subnet: 255.255.255.0
      
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensore-Presenza-bt-Auto-Garage"
    password: "xxx"

esp32_ble_tracker:
  on_ble_advertise:
    - then:
        - lambda: |-
            std::string nome_bluetooth = x.get_name();
            // Controllo per Tesla 1
            if (nome_bluetooth == "id tesla") {
              id(tesla_c_rilevata) = true;
              id(last_seen_1) = millis();
            }
            // Controllo per 2
            else if (nome_bluetooth == "id Tesla 2") {
              id(tesla_1_rilevata) = true;
              id(last_seen_1) = millis();
            }

# Variabili Globali per Debounce Temporale
globals:
  # Tesla 1
  - id: tesla_1_rilevata
    type: bool
    restore_value: no
    initial_value: "false"
  - id: last_seen_c
    type: unsigned long
    restore_value: no
    initial_value: "0"

  # Tesla 2
  - id: tesla_2_rilevata
    type: bool
    restore_value: no
    initial_value: "false"
  - id: last_seen_mia
    type: unsigned long
    restore_value: no
    initial_value: "0"

# Sensore di Presenza per Tesla 1 con Debounce
binary_sensor:
  - platform: template
    name: "Presenza Tesla 1"
    device_class: presence
    id: presenza_tesla_1
    lambda: |-
      // Controlla se Tesla 1 è stata vista negli ultimi 10 secondi
      if (id(tesla_1_rilevata) && (millis() - id(last_seen_c) < 60000)) {
        return true;
      }
      else {
        return false;
      }

# Sensore di Presenza per Tesla 2 con Debounce
  - platform: template
    name: "Presenza Tesla 2"
    device_class: presence
    id: presenza_tesla_2
    lambda: |-
      // Controlla se Tesla 2 è stata vista negli ultimi 10 secondi
      if (id(tesla_mia_rilevata) && (millis() - id(last_seen_2) < 60000)) {
        return true;
      }
      else {
        return false;
      }
``
# Automation Interna per Aggiornamento Ogni Secondo
interval:
  - interval: 5s
    then:
      # Per Tesla 1
      - lambda: |-
          static bool last_state_1 = false;
          bool current_state_1 = id(presenza_tesla_1).state;
          // Invia lo stato solo se c'è un cambio reale di stato
          if (current_state_1 != last_state_1) {
            id(presenza_tesla_1).publish_state(current_state_1);
            last_state_1 = current_state_1;
          }

      # Per Tesla 2
      - lambda: |-
          static bool last_state_2 = false;
          bool current_state_2 = id(presenza_tesla_2).state;
          // Invia lo stato solo se c'è un cambio reale di stato
          if (current_state_2 != last_state_2) {
            id(presenza_tesla_2).publish_state(current_state_2);
            last_state_2 = current_state_2;
          }

```

**Comment by guyank** [comment]
> Just for comparison of sensor stability this is the data of presence for the 3 sensors over the past week.
> 
> <img alt="Image" width="1258" src="https://private-user-images.githubusercontent.com/1818975/415401967-d842c033-d948-4962-9bc7-9a70f00c0644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQyODAxNzgsIm5iZiI6MTc0NDI3OTg3OCwicGF0aCI6Ii8xODE4OTc1LzQxNTQwMTk2Ny1kODQyYzAzMy1kOTQ4LTQ5NjItOWJjNy05YTcwZjAwYzA2NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTBUMTAxMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTcyZDY2NGI2ZmY3NDI5YWQ1ZmMyMDJmYjIyZTUzNWYzZjU5MjhiZmY2MzI0N2U1NTI5MmZiODY3YzVjNmU5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hP08ArQyJzoE7Ggr09JCJi_MqOO5s004XfAaYUonff4">
> I made some config changes on Feb19 to the RPi 4 which appear to have maybe improved stability on the sensors... And I don't see any HCI errors in dmesg since making the following changes either.
> 
> **What I did:**.
> 
> 1. Ran rpi-update to update to latest kernel and firmware.
> 2. Disabled sap by chaging the systemd unit for bluetooth.service to use this.
>    ExecStart=/usr/libexec/bluetooth/bluetoothd --noplugin=sap
> 3. Added the following 2 configurations to /etc/bluetooth/main.conf.
>    FastConnectable = true
>    TemporaryTimeout = 0
> 
> Look at the changes in the sensor stability before and after these changes, I can see a pretty decent improvement in how often it flip/flops on even the non BC sensor.
> 
> More testing i'd say will help prove the value of these changes, but if it does pan out to improve for others, might be worthwhile adding into the docs these changes :)

I was having problems with it becoming unresponsive at any point between a few hours and a few days. I think this was because commands weren’t sent as the container thought the vehicle had gone from intermittently present as you’re seeing, to permanently not present. I followed your first step to update the Pi firmware and that’s improved the stability, but still seeing intermittent presence. Thanks for the tip
