### ISSUE TITLE
parse error: Invalid numeric literal

### ISSUE THREAD

**Issue by jipema** [tesla-local-control/tesla_ble_mqtt_docker#74]
I'm currently testing the v0.0.4a-dev, and encountering some parsing issues in the logs, both for a Model 3 2024 and a Model Y 2022:

`getStateValueAndPublish; failed to parse .climateState.driverTempSetting for vin:LRW3Exxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1282`

`getStateValueAndPublish; failed to parse .tirePressureState.tpmsPressureRl for vin:LRW3Exxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 693`

`getStateValueAndPublish; failed to parse .closuresState.doorOpenDriverRear for vin:LRWYGxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 718`

Usually followed by:
`Invalid configuration request:tesla_ble/LRW3Exxxxxxxxxxxx/config topic:tesla_ble/LRW3Exxxxxxxxxxxx/config vin:LRW3Exxxxxxxxxxxx`

Let me know if/how you need more details, would be happy to help this neat project!

**Comment by iainbullock** [comment]
Thanks for posting this information. As this is a development version it has not had much testing so I can't say yet what is wrong. I have a few questions / things for you to try:

You have it setup for two cars at once? That should work but you are probably first to test it!

I assume you are polling? If so what polling interval have you set for each car?

If you turn polling off for both cars and Press the Force Update All button does it do the same?

Is it repeatable ie always does the same with the same entities?

If you can send me the full set of logs from when the container starter until just after the errors?

That's it for now maybe your answers will give a clue!

Regards Iain

**Comment by jipema** [comment]
I'm indeed using it with two cars at once: livin' on the edge! 😎 

Polling intervals are both set at 660s.

Parsing issue is repeatable, but not consistent: sometimes my entities get values, sometimes they end up `unknown` (when parsing error occurs?).

I tried the previous version, last week, only sending commands, and that worked fine.

I will definitely disable polling, both and individually, and let you know. 
Also maybe removing one VIN from the setting to compare.

**Comment by jipema** [comment]
So, I tried these combinations:
- 2 vins, both polling on
- 2 vins, both polling off
- 2 vins, 1 polling off
- 1 vin, polling on
- 1 vin, polling off
Unfortunately, they all encounter some random (I think) parsing error.
Here is the full log:

```[21:56:01] Starting... loading /app/env.sh
[21:56:01] loading libproduct.sh
Setting up MQTT clients with authentication
Configuration Options are:
  BLE_CMD_RETRY_DELAY=5
  DEBUG=false
  MQTT_SERVER=xxx.xxx.xxx.xxx
  MQTT_PORT=1883
  MQTT_PASSWORD=Not Shown
  MQTT_USERNAME=xxxxxx
  PRESENCE_DETECTION_LOOP_DELAY=120
  PRESENCE_DETECTION_TTL=240
  TEMPERATURE_UNIT_FAHRENHEIT=false
  VIN_LIST=LRWYxxxxxxxxxxxxxx
  MAX_CURRENT=16
  NO_POLL_SECTIONS=drive
  ENABLE_HA_FEATURES=true
Removing single buttons to be replaced by switches & covers:
windows, charger, charge-port, climate, trunk
delete_legacies_singles; deleting legacy single MQTT entities topics
vin:LRWYxxxxxxxxxxxxxx presence has expired, set presence ON
setupHADiscoveryAllVINsMain; Discarding unread MQTT messages for command and config topics
Listening for Home Assistant Start (in background)
Entering main loop...
main loop; Launching background listen_to_mqtt_loop...
Entering Listen to MQTT loop...
Launching listen_to_mqtt
Listening to MQTT
main loop; Launching background poll_state_loop...
main loop; launch BLE scanning for car presence every 120 seconds
Entering poll_state_loop...
check_presence; found BLE MAC addr:B8:55:48:xx:xx:xx for BLE_LN:S8d405c77fdcxxxxxx
vin:LRWYxxxxxxxxxxxxxx ble_ln:S8d405c77fdcxxxxxx match:(S8d405c77fdcxxxxxx|FF:FF:FF:FF:FF:FF) presence detected
vin:LRWYxxxxxxxxxxxxxx presence has expired, set presence ON
Received MQTT message; topic:tesla_ble/LRWYxxxxxxxxxxxxxx/config msg:read-state-all vin:LRWYxxxxxxxxxxxxxx cmd:config
read-state; calling readState()
sendBLECommand: Attempt 1/5 sending Send state command with category=charge to vin:LRWYxxxxxxxxxxxxxx command:state charge
teslaCtrlSendCommand; Error: context deadline exceeded
Vehicle might be asleep, or not present. Sending wake command
sendBLECommand; Retrying in 5 seconds
sendBLECommand: Attempt 2/5 sending Send state command with category=charge to vin:LRWYxxxxxxxxxxxxxx command:state charge
Command state charge was successfully delivered to vin:LRWYxxxxxxxxxxxxxx
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/awake to true
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.batteryLevel for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.batteryRange for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargerPower for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargerActualCurrent for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargerVoltage for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargeEnergyAdded for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargeMilesAddedRated for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargeRateMph for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.connChargeCable for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargeEnableRequest for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargePortDoorOpen for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargeCurrentRequest for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 1681
getStateValueAndPublish; failed to parse .chargeState.chargeLimitSoc for vin:LRWYxxxxxxxxxxxxxx
sendBLECommand: Attempt 1/5 sending Send state command with category=climate to vin:LRWYxxxxxxxxxxxxxx command:state climate
Command state climate was successfully delivered to vin:LRWYxxxxxxxxxxxxxx
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/awake to true
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/sensor/inside_temp to 5.8000007
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/sensor/outside_temp to 5.5
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/sensor/passenger_temp to 19.5
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/number/driver_temp_setting to 19.5
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/switch/is_climate_on to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/switch/steering_wheel_heater to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/battery_heater_on to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/front_defrost to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/rear_defrost to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/wiper_heater to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/mirror_heater to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/select/seat_heater_left to off
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/select/seat_heater_right to off
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/select/seat_heater_rear_left to off
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/select/seat_heater_rear_right to off
sendBLECommand: Attempt 1/5 sending Send state command with category=tire-pressure to vin:LRWYxxxxxxxxxxxxxx command:state tire-pressure
Command state tire-pressure was successfully delivered to vin:LRWYxxxxxxxxxxxxxx
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/awake to true
jq: parse error: Invalid numeric literal at line 1, column 693
getStateValueAndPublish; failed to parse .tirePressureState.tpmsPressureFl for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 693
getStateValueAndPublish; failed to parse .tirePressureState.tpmsPressureFr for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 693
getStateValueAndPublish; failed to parse .tirePressureState.tpmsPressureRl for vin:LRWYxxxxxxxxxxxxxx
jq: parse error: Invalid numeric literal at line 1, column 693
getStateValueAndPublish; failed to parse .tirePressureState.tpmsPressureRr for vin:LRWYxxxxxxxxxxxxxx
sendBLECommand: Attempt 1/5 sending Send state command with category=closures to vin:LRWYxxxxxxxxxxxxxx command:state closures
Command state closures was successfully delivered to vin:LRWYxxxxxxxxxxxxxx
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/awake to true
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/switch/sentry_mode to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/cover/rear_trunk to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/frunk_open to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/window_open_driver_front to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/window_open_pass_front to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/window_open_driver_rear to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/window_open_pass_rear to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/door_open_driver_front to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/door_open_pass_front to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/door_open_driver_rear to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/door_open_pass_rear to false
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/lock/locked to true
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/cover/windows to false
sendBLECommand: Attempt 1/5 sending Send state command with category=drive to vin:LRWYxxxxxxxxxxxxxx command:state drive
Command state drive was successfully delivered to vin:LRWYxxxxxxxxxxxxxx
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/binary_sensor/awake to true
driveState; sendBLECommand succeeded for vin:LRWYxxxxxxxxxxxxxx
Setting MQTT topic tesla_ble/LRWYxxxxxxxxxxxxxx/sensor/odometer to 30303
vin:LRWYxxxxxxxxxxxxxx ble_ln:S8d405c77fdcxxxxxx match:(S8d405c77fdcxxxxxx|B8:55:48:xx:xx:xx) presence detected```

**Comment by iainbullock** [comment]
Thanks for the detailed response. I appreciate it takes some time, but it helps me understand what the issue might be. More questions and things to try again!

When you say you used the previous version do you know which one it was? A newer production version v0.3.0 was released last week which read state but didn't poll. Before that the production release was v0.2.2 see https://github.com/tesla-local-control/tesla_ble_mqtt_docker/releases

I'd be interested for you to try v0.3.0. It requires you to press the 'Force Data Update' button to read the state. Some messing around for you I appreciate.

Alternatively turn on debugging by setting the environment variable to true and see what it of interest in the logs. You can send me the whole lot of debug logs if you like, but it will be a lot,  and work for you if you want to obsfurcate the VINs (not sure you need to). Or just scan through yourself and send me what is of interest. In particular I'd like to see the JSON from the call to tesla-control when reading state. Especially if you can get one of the same state category which works and one which doesn't.

Finally what hardware are you using and how far away form the car(s) is it?

I hope that makes sense

Thanks

**Comment by jipema** [comment]
I've downgraded to v0.3.0, and enabled debug. Here is an extract of an encountered parsing issue:

```
sendBLECommand: Attempt 1/5 sending Send state command with category=tire-pressure to vin:LRW3xxx command:state tire-pressure
sendBLECommand; {
  "tirePressureState":  {
    "timestamp":  "2025-01-09T09:31:48.439Z",
    "tpmsPressureFl":  2.8500001,
    "tpmsPressureFr":  2.875,
    "tpmsPressureRl":  2.8500001,
    "tpmsPressureRr":  2.9,
    "tpmsLastSeenPressureTimeFl":  "2025-01-08T17:38:53.438Z",
    "tpmsLastSeenPressureTimeFr":  "2025-01-08T17:38:53.438Z",
    "tpmsLastSeenPressureTimeRl":  "2025-01-08T17:38:53.438Z",
    "tpmsLastSeenPressureTimeRr":  "2025-01-08T17:39:23.438Z",
    "tpmsHardWarningFl":  false,
    "tpmsHardWarningFr":  false,
    "tpmsHardWarningRl":  false,
    "tpmsHardWarningRr":  false,
    "tpmsSoftWarningFl":  false,
    "tpmsSoftWarningFr":  false,
    "tpmsSoftWarningRl":  false,
    "tpmsSoftWarningRr":  false,
    "tpmsRcpFrontValue":  2.9,
    "tpmsRcpRearValue":  2.9
  }
}
 Got an unregistered notification
Command state tire-pressure was successfully delivered to vin:LRW3xxx
readTyreState; sendBLECommand succeeded for vin:LRW3xxx
jq: parse error: Invalid numeric literal at line 1, column 693
getStateValueAndPublish; failed to parse .tirePressureState.tpmsPressureFl for vin:LRW3xxx return:2
```

The JSON seems valid to me. Naive questions: isn't it because it is trying to parse what already seems to be a float value? Or is it an issue with the number of decimals maybe?

I'm using a raspberry pi zero 1.1 W, its about 2 meters from the car.

**Comment by iainbullock** [comment]
I agree the JSON looks ok. 

I tested it by putting the JSON into a file called json, and executing cat json | jq -e '.tirePressureState.tpmsPressureFl'

Result was: 2.8500001 

So it think it should parse OK

Are the lines in the logs above sequential after the JSON is printed out or have you removed some? 

'Got an unregistered notification' I have seen this before, it happens to me if the state read fails for some reason. I would get it if I read the state categories too quickly in succession. I am using a RPi3b+ approx 2 metres from the car with BLE_CMD_RETRY_DELAY=2. Setting a lower value here gave me unreliable state reads. You have it set to 5 which should be fine. Maybe try a larger value but really it will become very slow if that ends up being the solution

I note that raspberry pi zero 1.1W uses BLE version 4.1. I read somewhere that Tesla changed the minimum version to 5.x (without telling anyone) in the more recent versions (supporting state reads) of https://github.com/teslamotors/vehicle-command. I can't find the reference anywhere so might be a red herring

Is it possible the JSON above is from a successful attempt, but there is no JSON / the 'Got an unregistered notification' message occurs when it is unsuccessful?

How comfortable are you modding the code inside the container to add  some extra diagnostics? If you are up for it, turn off debugging and restart. Then while it's running, get a command line on your host and type:  
```
docker exec -it tesla_ble_mqtt /bin/sh
```
This give a shell inside the container. You can then mod the code by doing this:

```
cd app
vi read_state.sh
```

Find these lines:
```
  # Get value from JSON, and publish to MQTT
  rqdValue=$(echo $stateJSON | jq -e $jsonParam)
  EXIT_STATUS=$?
```
add some echo commands like this:
```
  # Get value from JSON, and publish to MQTT
  rqdValue=$(echo $stateJSON | jq -e $jsonParam)
  EXIT_STATUS=$?
echo stateJSON: $stateJSON  
echo rqdValue: $rqdValue
echo EXIT_STATUS $EXIT_STATUS
```
Restart container (not restart the stack which overrights the mod). Check the logs to see what results you get when it works and when it doesn't

I appreciate its work for you, but it helps the project if you are able to do it

Thanks

**Comment by jipema** [comment]
Here is the log extract at a failure point including the added echo:
```
2025/01/09 17:17:21 Got an unregistered notification
Command state charge was successfully delivered to vin:LRWYXXXXXXXXXXXX
readChargeState; sendBLECommand succeeded for vin:LRWYXXXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 1643
stateJSON: { "chargeState": { "chargingState": { "Complete": {} }, "fastChargerType": { "ACSingleWireCAN": {} }, "fastChargerBrand": { "Tesla": {} }, "chargeLimitSoc": 80, "chargeLimitSocStd": 80, "chargeLimitSocMin": 50, "chargeLimitSocMax": 100, "maxRangeChargeCounter": 0, "fastChargerPresent": false, "batteryRange": 200.08733, "estBatteryRange": 188.70114, "idealBatteryRange": 200.08733, "batteryLevel": 81, "usableBatteryLevel": 80, "chargeEnergyAdded": 0.9, "chargeMilesAddedRated": 4, "chargeMilesAddedIdeal": 4, "chargerVoltage": 2, "chargerPilotCurrent": 16, "chargerActualCurrent": 0, "chargerPower": 0, "tripCharging": false, "chargeRateMph": 0, "chargePortDoorOpen": true, "connChargeCable": { "IEC": {} }, "scheduledChargingPending": false, "scheduledDepartureTime": "2024-12-04T05:30:00Z", "chargeEnableRequest": true, "chargerPhases": 2, "chargePortLatch": { "Engaged": {} }, "chargePortColdWeatherMode": false, "chargeCurrentRequest": 13, "chargeCurrentRequestMax": 16, "timestamp": "2025-01-09T17:17:19.930Z", "preconditioningTimes": { "allWeek": {} }, "offPeakChargingTimes": {}, "scheduledChargingMode": "ScheduledChargingModeOff", "chargingAmps": 13, "preconditioningEnabled": false, "scheduledChargingStartTimeApp": -1, "superchargerSessionTripPlanner": false, "chargePortColor": "ChargePortColorGreen", "chargeRateMphFloat": 0, "managedChargingState": { "chargeOnSolarState": { "notAllowed": {} }, "chargeOnSolarGatewayDin": "", "teslaElectricAssetId": "" }, "chargeCableUnlatched": false, "homeLocation": { "latitude": xxxxx, "longitude": xxxxx }, "workLocation": { "latitude": xxxx, "longitude": xxxx } } } 2025/01/09 17:17:21 Got an unregistered notification
jsonParam .chargeState.batteryLevel
rqdValue: 81
EXIT_STATUS 5
getStateValueAndPublish; failed to parse .chargeState.batteryLevel for vin:LRWYXXXXXXXXXXXX return:2
readChargeState; one of the getStateValueAndPublish calls failed for vin:LRWYXXXXXXXXXXXX return:3
readState; failed to read charge state vin:LRWYXXXXXXXXXXXX. Exit status: 3
```
It seems indeed it always fail following a `Got an unregistered notification` error, which is surprising as the json seem fine somehow.

I will try to increase the retry delay. 
I can also try to run it on a raspi3b, I think I might have one around.

**Comment by iainbullock** [comment]
Is the '2025/01/09 17:17:21 Got an unregistered notification' part of $stateJSON or is that where it got printed? If it's part of the JSON then I'm sure it will mess something up. 

Also I've not seen a EXIT_STATUS of 5 it's not documented. It did actually parse the JSON correctly, so if an EXIT_STATUS of 5 is demmed to be succesful in the test, it might work ok

**Comment by iainbullock** [comment]
OK

I ran $stateJSON through jq manually. If '2025/01/09 17:17:21 Got an unregistered notification' is on the end it does as above, i.e. parses the result but then an EXIT_STATUS of 5

If I do the same without the '2025/01/09 17:17:21 Got an unregistered notification', it parses correctly but the EXIT_STATUS = 0

I still suspect the Got an unregistered notification is due to the bluetooth communication struggling in someway, however we could make the code more robust perhaps by accepting an ERROR_STATUS of 5 AND a non null rqdValue

If you change
```
if [ $EXIT_STATUS -eq 0 ] || { [ $EXIT_STATUS -eq 1 ] && [ $rqdValue == "false" ]; } || { [ $EXIT_STATUS -eq 1 ] && [ $jsonParam == ".chargeState.connChargeCable" ]; }; then
```
to
```
if [ $EXIT_STATUS -eq 0 ] || { [ $EXIT_STATUS -eq 1 ] && [ $rqdValue == "false" ]; } || { [ $EXIT_STATUS -eq 1 ] && [ $jsonParam == ".chargeState.connChargeCable" ]; } || { [ $EXIT_STATUS -eq 5 ] && [ -z $rqdValue ]; }; then
```
It will be interesting to see if it then works.

Even if it does and you have time it would be helpful if you could test the unmodified code on the RPI3

Thanks Iain

**Comment by jipema** [comment]
I haven't had the time to test the EXIT_STATUS change suggestion, but in the meantime I've added some cleaning to the json string before the parsing, and it seems to solve the issue:
`stateJSON=$(echo "$stateJSON" | sed 's/\([0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}\).*$//')`

Off course, it's a workaround, as we should rather find the reason for the `Got an unregistered notification` in the json. I will try on a raspberry pi 3b asap.

**Comment by iainbullock** [comment]
Good workaround! That regex syntax always makes my eyes funny, so I'll believe you!

I will include something like this into the next dev release, but it needs to be detected and throw a warning rather then just letting it go unnoticed, as I think it's a sign of unreliability that might crop up elsewhere

I hope the RPi3 does the trick, though I have just checked and it is BLE version 4.2. Could be something else with the hardware, so I still think it's worth you trying it

Thanks again

**Comment by iainbullock** [comment]
I put the following code in the new dev version which I hope will flag if this happens to someone else. I can't test it, so if you have time I'd appreciate it.

Thanks again
```
function getStateValueAndPublish() {
  vin=$1
  mqttTopic=$3
  stateJSON=$4

  # Check for json having unwanted text at the end. This might be a sign of a bluetooth hardware issue or sending commands too quickly
  # See https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/74
  jsonParam=$( echo "$2" | sed 's/\([0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}\).*$//' )
  if [ "$jsonParam" != "$2" ]; then
    log_warning "poll_state: tesla-control returned unclean JSON. See https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/74"
  fi
  
  # Get value from JSON, and publish to MQTT
  rqdValue=$(echo $stateJSON | jq -e $jsonParam)
  EXIT_STATUS=$?
```

**Comment by iainbullock** [comment]
I took a risk and released v0.4.1a-dev on DockerHub. It has a lot of improvements (and I'm sure some bugs). 

I hope it also implements an effective workaround for this issue. Thanks for your support

**Comment by jipema** [comment]
Hi Iain,

Thanks for the update and the efforts.

I just tried the v0.4.1a-dev and, unfortunately, something's still off:
```
MQTT topic tesla_ble/LRW3XXXXXXXXXXX/sensor/tpms_pressure_rr successfully updated to 2.9750001
sendBLECommand: Attempt 1/5 sending Send state command with category=closures to vin:LRW3XXXXXXXXXXX command:state closures
Command state closures was successfully delivered to vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.sentryModeState for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.doorOpenTrunkRear for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.doorOpenTrunkFront for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.windowOpenDriverFront for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.windowOpenPassengerFront for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.windowOpenDriverRear for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.windowOpenPassengerRear for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.doorOpenDriverFront for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.doorOpenPassengerFront for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.doorOpenDriverRear for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.doorOpenPassengerRear for vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 718
getStateValueAndPublish; failed to parse .closuresState.locked for vin:LRW3XXXXXXXXXXX
MQTT topic tesla_ble/LRW3XXXXXXXXXXX/cover/windows successfully updated to false
sendBLECommand: Attempt 1/5 sending Send state command with category=drive to vin:LRW3XXXXXXXXXXX command:state drive
Command state drive was successfully delivered to vin:LRW3XXXXXXXXXXX
jq: parse error: Invalid numeric literal at line 1, column 312
```

I will enable debug and look into it.

**Comment by jipema** [comment]
I think I found the issue: Your change is cleaning `jsonParam` rather than `stateJSON`.
Here is a fix:
```
function getStateValueAndPublish() {
  vin=$1
  jsonParam=$2
  mqttTopic=$3

  # Check for json having unwanted text at the end. This might be a sign of a bluetooth hardware issue or sending commands too quickly
  # See https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/74
  stateJSON=$( echo "$4" | sed 's/\([0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}\).*$//' )
  if [ "$stateJSON" != "$4" ]; then
    log_warning "poll_state: tesla-control returned unclean JSON. See https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/74"
  fi
  
  # Get value from JSON, and publish to MQTT
  rqdValue=$(echo $stateJSON | jq -e $jsonParam)
```

And the result in the logs, warning about the issue but still parsing and publishing it properly:
```
poll_state: tesla-control returned unclean JSON. See https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/74
getStateValueAndPublish; .closuresState.sentryModeState parsed as false for vin:LRWYXXXXXXXX return:0
Setting MQTT topic tesla_ble/LRWYXXXXXXX/switch/sentry_mode to false
```

**Comment by iainbullock** [comment]
Arrgh a schoolboy error! Thanks again for debugging it and proposing a fix. I have now released v0.4.1b-dev on DockHub which I hope has it fixed.

When you get chance let me know what happens if you try different hardware.

Just an observation, when I was trying to test the (incorrect) mod yesterday, I was unable to get it to produce the unwanted string at the end of the JSON even when BLE_CMD_RETRY_DELAY was set to 0. Yet previously I've seen it happen with BLE_CMD_RETRY_DELAY=1 (I have it set at 1.5 normally). I currently have the RPi approx 1.5 metres from the rear right of the car. When I previously got it to produce the unwanted string, the car was facing the other direction, so the RPi was nearest to the front left. Completely anecdotal, and I didn't have time to test this theory yersterday.

**Comment by jipema** [comment]
I've updated to v0.4.1b-dev for few hours now, and it seems to work well!

Interesting observation regarding the distance/orientation of the car when the error is happening. In my case, the raspi is about a meter from the rear-left of the first car, and about 3 from the rear-left of the other one. Both are producing the error (randomly), so not sure its a distance thing... could it be some other interferences maybe?

Anyway, thanks for working on solving my issue, and thanks for this super useful project! 
I might have some other issues/suggestions, buts that's for another day, and another thread (or PR?).

**Comment by iainbullock** [comment]
Good to hear it's working. Are you still on the Rpi zero 1.1W ?

Thanks for your inputs, please submit any future improvements / ideas initially by raising an Issue. There are three devs on this project, we work on it as and when time allows. One of us might already be working on something similar. 

If you do submit a PR, do it against the #stage branch not #main. We use #stage to collect various changes and review amongst ourselves before we merge to #main

I'm probably the most active at the moment (it's not always the case), I tend to have what I'm working on in the #iain-dev branch

Thanks again

**Comment by jipema** [comment]
Indeed I'm still on the Rpi zero 1.1W, didn't find that rpi 3b yet. Will definitely let you know if tested.

**Comment by jipema** [comment]
Hi @iainbullock, out of curiosity and FYI, I unlisted the current BLE key from the cars, regenerated new ones, and repaired: this didn't fix the `Got an unregistered notification` issue.

I still havent had the opportunity to get my hands back on the raspi3 to compare it with the raspi zero 1.1w. I will let you know when done.
