### ISSUE TITLE
unable to install dev version

### ISSUE THREAD

**Issue by Nik18111997** [tesla-local-control/tesla_ble_mqtt_docker#93]
Hi i read your guide for developer install version, but when i check the logs i have this error, can you help me to solve them? thanks

![Image](https://github.com/user-attachments/assets/a73c92d5-78dd-4a98-abe9-fcac26d97550)

**Comment by dettofatto** [comment]
Did you try:

`Docker` compose pull ``

Before compose?

**Comment by Nik18111997** [comment]
No, tomorrow i try this command.

**Comment by iainbullock** [comment]
> Hi i read your guide for developer install version, but when i check the logs i have this error, can you help me to solve them? thanks
> 
> ![Image](https://github.com/user-attachments/assets/a73c92d5-78dd-4a98-abe9-fcac26d97550)

I'm not sure you have set the environment variables correctly. Please provide your docker-compose.yml and stack.env

**Comment by Nik18111997** [comment]
Hi the file docker-compose:

![Image](https://github.com/user-attachments/assets/104913a4-923b-44b5-aced-bb6bc98afc1c)

the stack.env:

![Image](https://github.com/user-attachments/assets/44058adf-5442-4689-b63a-af882a2f5dc1)

**Comment by iainbullock** [comment]
Looks ok. 

Plesae try to explicitly set a value for DEBUG by changing the line in stack.env:
DEBUG=true

I also noticed an error in my #iain-dev stack.env on GitHub, the line TC_KILL_TIMEOUT=25 was $TC_KILL_TIMEOUT=25, although the error isn't showing in your screenshot of stack.env. Interesting your screenshot of the logs above gave an error about the unexpected character "$", maybe you fixed it?

**Comment by Nik18111997** [comment]
yes, i fixed the, character "$", now it works correctly, i add a # on bluetooth line, i use a raspberry pi zero w v1.1, and raspberry pi os lite 32 bit, maybe the interface not present at this devices.

**Comment by iainbullock** [comment]
Your RPi has Bluetooth 4.1 built in so it should be detected. What are the logs showing now? Might be best to set DEBUG to false otherwise there are a lot of logs and it's hard to see what's happening

**Comment by Nik18111997** [comment]
I see 

Configuration Options are:
  BLE_CMD_RETRY_DELAY=5
  DEBUG=false
  MQTT_SERVER=192.168.1.5
  MQTT_PORT=1883
  MQTT_PASSWORD=Not Shown
  MQTT_USERNAME=XXXXXX
  PRESENCE_DETECTION_LOOP_DELAY=120
  PRESENCE_DETECTION_TTL=240
  TEMPERATURE_UNIT_FAHRENHEIT=false
  VIN_LIST=LRWXXXXXXXXXXX403
  MAX_CURRENT=32
  ENABLE_HA_FEATURES=true
Removing single buttons to be replaced by switches & covers:
windows, charger, cherge-port, climate, trunk
delete_legacies_singles; deleting legacy single MQTT entities topics  Setting up MQTT clients with authentication
setupHADiscoveryAllVINsMain; Discarding any unread MQTT messages for topic:tesla_ble/LRW3F7FS5RC036403/config
Listening for Home Assistant Start (in background)
Entering main loop...
main loop; Lauching background listen_to_mqtt_loop...
main loop; launch BLE scanning for car presence every 120 seconds
Entering Listen to MQTT loop...
Launching listen_to_mqtt
Listening to MQTT

Yes, I disabile debug now

**Comment by iainbullock** [comment]
You missed a few line of the log at the start which will tell us what version you are running. 

Does it work?

**Comment by iainbullock** [comment]
Excellent!
